### ISSUE TITLE
Error Nest cannot export a provider/module that is not a part of the currently processed module (UserModule). Please verify whether the exported UserService is available in this particular context.

### ISSUE THREAD

**Issue by amitsinghrawat1994** [phatvo21/nest-demo#1]
Hi,

I am new in nestJs and exploring this repo. I am extending authModule and want to use userService inside authService.

Can I use userService inside authService to see if the user already exists or not? 

Nestjs is throwing below error, Any hint and help would be great.

Error:
Nest cannot export a provider/module that is not a part of the currently processed module (UserModule). Please verify whether the exported UserService is available in this particular context.

Possible Solutions:
- Is UserService part of the relevant providers/imports within UserModule?

**Comment by amitsinghrawat1994** [comment]
This way it worked for me.

I have to export my userService same as the provider 

**user.module.ts**

```
import { UserService } from './user.service';
import { UserRepository } from './../../repositories/user.repository';
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { User } from './entity/user.entity';
import { UserController } from './user.controller';

@Module({
  imports: [TypeOrmModule.forFeature([User])],
  providers: [
    {
      provide: 'UserRepositoryInterface',
      useClass: UserRepository,
    },
    {
      provide: 'UserServiceInterface',
      useClass: UserService,
    },
  ],
  controllers: [UserController],
  exports: [
    {
      provide: 'UserServiceInterface',
      useClass: UserService,
    },
  ],
})
export class UserModule {}
```

To User it on AuthModule
First I Have to import userModule inside authModule

then inject service interface in authService

**auth.service.ts**

```
import { UserServiceInterface } from './../user/interface/user.service.interface';
import { Inject, Injectable } from '@nestjs/common';
import { RegisterUserDto } from './dto/register-user.dto';

@Injectable()
export class AuthService {
  constructor(
    @Inject('UserServiceInterface')
    private userService: UserServiceInterface,
  ) {}

  public async registerUser(registerUserDto: RegisterUserDto): Promise<void> {
    const isUserExist = await this.userService.isEmailExist(
      registerUserDto.email,
    );

    return;
  }
}
```

**Comment by phatvo21** [comment]
Hello @amitsinghrawat1994 , 
You have a pretty correct solution to resolve this problem. But, the best solution is to create a `SharedModule` and re-use that module in all places where using this module. 
For example: 
We need to use `userService` in the `authService` or somewhere in the application, then you can move this `userService` to `SharedModule` and declare it under global into the app module.
Feel free to contact my LinkedIn: https://www.linkedin.com/in/phat-dev/
I'll give you hand.

**Comment by amitsinghrawat1994** [comment]
Thanks for reply @phatvo21 

By using SharedModule is uncleared to me. I am googling it how to. 
Also, Please you can also update the repo with your solution when you will be available. 
:-)
